### ISSUE TITLE
Newer versions of Numpy cause breaking changes to using Seak

### ISSUE THREAD

**Issue by meyerkm** [HealthML/seak#7]
When using new versions of Numpy and trying to `pip install -e ./seak/ `, I encounter breaking changes in your code.  Would it be possible to update your code base to allow _seak_ to compile under newer numpy/Cython/setuptools versions?

Relevant package versions in my env: 
```
python      3.12.7
cython      3.0.11
numpy        2.1.3  
setuptools  75.6.0
```

Error : 
```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      cimport numpy
      cimport cython

      ctypedef numpy.float64_t DTYPE_float
      ctypedef numpy.int_t DTYPE_int
               ^
      ------------------------------------------------------------

      src/seak/optimizer.pyx:10:9: 'int_t' is not a type identifier
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/usr/seak/setup.py", line 100, in <module>
          ext_modules=cythonize(ext_modules),
                      ^^^^^^^^^^^^^^^^^^^^^^
        File "/data/conda/.conda/envs/myenv/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/data/conda/.conda/envs/myenv/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/seak/optimizer.pyx
      Compiling src/seak/optimizer.pyx because it changed.
      [1/1] Cythonizing src/seak/optimizer.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by Antonio-Nappi** [comment]
I had the same issue, and I fixed in this way:
1. downgrade to numpy <2 
2. install seak
3. upgrade back numpy
